apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: redis
    role: slave
  name: redis-slave
spec:
  replicas: 2
  selector:
    app: redis
    role: slave
  template:
    metadata:
      labels:
        app: redis
        role: slave
    spec:
      containers:
      - image: kubernetes/redis-slave:v2
        name: redis-slave
        ports:
        - containerPort: 6379
          name: redis-server

