apiVersion: v1
kind: ReplicaSet
metadata:
  name: redis-master
spec:
  replicas: 1
  matchLabels:
    selector:
      app: redis
      role: master
  template:
    metadata:
      labels:
        app: redis
        role: master
    spec:
      containers:
      - image: redis:2.8.23
        name: redis-master
        ports:
        - containerPort: 6379
          name: redis-server

